### ISSUE TITLE
Code Blocks Font Size?

### ISSUE THREAD

**Issue by rjhilgefort** [gsuitedevs/md2googleslides#17]
I'm finding it painful to work around not having any control over the font size of the generated code blocks. Do you have any suggestions or workarounds for making the font size smaller? I didn't see a `font-size` option for the `span` tags.

**Comment by sqrrrl** [comment]
Ideally I'd prefer to see auto-resizing supported in Slides itself.

As a quick hack, yeah, adding font-size support would be pretty easy to do -- mostly just propagating it through a handful of places:

https://github.com/googlesamples/md2googleslides/blob/master/src/extract_slides.js#L97
https://github.com/googlesamples/md2googleslides/blob/master/src/extract_slides.js#L578
https://github.com/googlesamples/md2googleslides/blob/master/src/generic_layout.js#L120

Ideally I'd like to see Slides support a size-to-fit option so it can be done dynamically. It's likely possible to do that in the tool itself, but a fair amount of work to do calculate the layouts correctly.

**Comment by sqrrrl** [comment]
Added font-size support in next release (0.4) -- you can now override the font-size for most markdown elements:

<pre>
# Slide
--- {style="font-size:12pt"}
code here..
---
</pre>

example.md has been updated to show this.

**Comment by rjhilgefort** [comment]
👏👏👏 Awesome!
