### ISSUE TITLE
Make this a Google Slides script

### ISSUE THREAD

**Issue by frankiesardo** [gsuitedevs/md2googleslides#18]
It would be great if this was a script we can run in Google Slides.
Ideally I can open a dropdown with a text area and paste my markdown there, press save and see the slide deck automatically changing itself. I can always visualise and edit the source markdown from the tab and make further changes. What do you think about this?

**Comment by sqrrrl** [comment]
I like the idea, but it would best be done as a separate project. It might be possible to take some of this code and convert it something that can be run as a service in Google Cloud Functions. You could then create a small wrapper add-on for Slides that posted the markdown & the doc ID to the service (along w/access token) to do the updates.
