### ISSUE TITLE
Code block language type should not be enforced

### ISSUE THREAD

**Issue by fonnesbeck** [gsuitedevs/md2googleslides#23]
It appears to be impossible to specify a code block without specifying a language. If you do, you get:

    Unable to generate slides: Error: Unknown language: ` ` is not registered

It would be great to not have to specify a language, but just have unformatted text. It does not appear that the language types are based on linguist, which is most common here. Is there a list of supported languages?

**Comment by sqrrrl** [comment]
Code mostly handled this already if the new line comes directly after the triple back ticks. Any whitespace after though would cause this. Adding some code to trim the value before checking.

**Comment by sqrrrl** [comment]
Trimming fixed in next release (0.4)
