### ISSUE TITLE
Read from STDIN

### ISSUE THREAD

**Issue by rossmeissl** [gsuitedevs/md2googleslides#24]
It would be great to be able to pipe Markdown to md2googleslides rather than having to save to a file first! Thank you ❤️

**Comment by sqrrrl** [comment]
Added a (slightly hacky) way to do this that will appear in 0.4 when I release it shortly. Use the placeholder STDIN as the file name and you'll be able to pipe in the markdown.

I'm going to rework the command line options in 0.5 and will make it a bit cleaner in the future.

**Comment by rossmeissl** [comment]
Thanks so much @sqrrrl!
