### ISSUE TITLE
Example `examples/example.md` throws 500 error

### ISSUE THREAD

**Issue by grant** [gsuitedevs/md2googleslides#27]
The [example.md](https://github.com/gsuitedevs/md2googleslides/blob/master/examples/example.md) throws a 500 error. All examples should be working.

```
"code": 500,
  "errors": [
    {
      "message": "Internal error encountered.",
      "domain": "global",
      "reason": "backendError",
      "debugInfo": ...
```

**Comment by sqrrrl** [comment]
Appears to be an internal error related to loading images, an an intermittent one at that. Seems to fail ~50% of the time for me when loading images from a particular source (unsplash.com). Filed a bug against the Slides API.

Will update the example presentation to load from elsewhere.

**Comment by sqrrrl** [comment]
Switching to https://picsum.photos/ seems to work more reliably.
