### ISSUE TITLE
Internal 500 error with specific link formats

### ISSUE THREAD

**Issue by cyanliu** [gsuitedevs/md2googleslides#28]
When slides are formatted with a title and a link with text following it in a bullet point (denoted with either `-` or `*`), it seems to throw an error.

For example, the following slide would error out
```
---
# Slide title

- text bullet

- [This is hyperlink text](http://www.example.com/) this is text after the hyperlink
---
```

But the following slide would be fine:
```
---
# Slide title

- text bullet

- This is text before the hyperlink, [this is hyperlink text](http://www.example.com/) this is text after the hyperlink
---
```

And the error message is as follows:
```
{
  "code": 500,
  "errors": [
    {
      "message": "Internal error encountered.",
      "domain": "global",
      "reason": "backendError"
    }
  ]
}
```

**Comment by sqrrrl** [comment]
From what I can tell this is an issue with the Slides API. Filed a bug and will update when I have more information.

**Comment by sqrrrl** [comment]
Confirmed this was an issue with the API itself and a fix has already been submitted (not yet pushed to prod though.)

**Comment by cyanliu** [comment]
Awesome; thank you for the quick response and followups!
