### ISSUE TITLE
Math support

### ISSUE THREAD

**Issue by tgirke** [gsuitedevs/md2googleslides#33]
`md2googleslides` is a very useful tool. Thanks for the great work. - One feature that is missing (or I couldn't find) is math support (similar to here: http://bit.ly/2RUnjKO). Are there any plans to add it in the future?

**Comment by sqrrrl** [comment]
Yes, I did start looking in to supporting MathJax via https://github.com/pkra/mathjax-node-svg2png. But I need to implement image upload first.

**Comment by sqrrrl** [comment]
Blocked by #31

**Comment by pkra** [comment]
@sqrrrl I haven't maintained mathjax-node-svg2png in a while (since piping to puppeteer is often easier). Please feel free to ping me if there's something i can help with.

**Comment by sqrrrl** [comment]
@pkra Thanks for the heads up. Not a huge deal as there are lots of options for the SVG->png conversion.

**Comment by sqrrrl** [comment]
Fixed in master, will be in next release (0.5). Should get around to pushing that shortly.
