### ISSUE TITLE
QUESTION: How to extend this generator with custom elements and syntax.

### ISSUE THREAD

**Issue by BioPhoton** [gsuitedevs/md2googleslides#34]
It there an easy way to extend this code in a way that it creates out of this string:

-o-o->

these shapes:

![test](https://user-images.githubusercontent.com/10064416/49801804-77422c00-fd4b-11e8-9013-280e52024347.PNG)

I'm looking for general approaches and the right line of code to start from. 

:-)

Thanks in advance!
Michael

**Comment by erickoledadevrel** [comment]
I think you'd first need to build an extension to the [markdown-it library](https://github.com/markdown-it/markdown-it#syntax-extensions), which this sample uses to parse the markdown. Once you can detect entities like the one you listed, you then would need to add code to [src/extract_slides.js](https://github.com/gsuitedevs/md2googleslides/blob/master/src/extract_slides.js) to handle the parsed token and add the correct shapes. It would not be a simple task.
