### ISSUE TITLE
NPM package doesn't support the '--copy' command listed in the example.md file

### ISSUE THREAD

**Issue by mbforr** [gsuitedevs/md2googleslides#39]
Hi there I wanted to use the `--copy [presentation id]` command listed in the example.md file but it isn't available in the package on NPM. Will this be updated or how could I use it?

**Comment by mbforr** [comment]
mainly wanted to use it with this command `{layout="Split Title and Code"}` to use a master set of slides. Thanks!

**Comment by erickoledadevrel** [comment]
@sqrrrl - Looks like you need to cut a new release.

**Comment by sqrrrl** [comment]
Yep. Was hoping to get some other features in (local file support + MathJax support) but stalled on it due to the access_token issue. Will see if I can get over that hump and get a new release out.

**Comment by mbforr** [comment]
awesome thanks a ton! i found a workaround for the time being by creating a copy of a template deck in google drive then running `md2gslides /path/to/file/example.md -e -a [ID_OF_THE_TEMPLATE_COPY]`

on a separate note, was curious about adding support for images for drop shadows and transparency. any thoughts on best ways to do that? happy to take a stab at it as well.

**Comment by erickoledadevrel** [comment]
I believe this is now fixed: https://github.com/gsuitedevs/md2googleslides/issues/40#issuecomment-483782419

**Comment by sqrrrl** [comment]
Pushed a new package with --copy.

As for adding transparency and drop shadows, added issue #47 to track that. Most of the plumbing is already in place in terms of attaching attributes/styles to images, just need to plumb it through and translate them into an UpdateImageProperties request to set the attributes.
