### ISSUE TITLE
Error: Cannot find module '../lib/auth'

### ISSUE THREAD

**Issue by tducret** [gsuitedevs/md2googleslides#40]
Hello !

I really ❤️  **md2gslides** ! Thank you very much.
I am even writing an article about it (in French) :)
I'd like to create a minimal docker image with it but I'm having problems installing it from the sources (I confess I am a noob in node).
*I am using the sources because I'd like to use the `--copy` and `{layout=...}` options 

Could you please help me?

Here is the log : 

```bash
# npm install -g https://github.com/gsuitedevs/md2googleslides
/usr/local/bin/md2gslides -> /usr/local/lib/node_modules/md2gslides/bin/md2gslides.js
+ md2gslides@0.4.0
added 169 packages from 477 contributors in 27.138s
# md2gslides
module.js:550
    throw err;
    ^

Error: Cannot find module '../lib/auth'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/md2gslides/bin/md2gslides.js:25:24)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by tducret** [comment]
Any idea please?

Also, I'd like to let you know that I built a Docker image for **md2googleslides** with a wrapper script > https://github.com/tducret/md2gs

**Comment by erickoledadevrel** [comment]
Glad you enjoy it! I believe @sqrrrl was planning to cut a new release soon with those features.

**Comment by sqrrrl** [comment]
Yep, a new version with the --copy flag (and some other goodies) was recently published, should be able to go back to just using the packaged version.

**Comment by tducret** [comment]
Thanks @sqrrrl 
I updated the docker image yesterday with the new md2gslide > https://github.com/tducret/md2gs
