### ISSUE TITLE
SVG not working - apparently local image

### ISSUE THREAD

**Issue by hchiam** [gsuitedevs/md2googleslides#59]
# Good: 
`md2gslides slides.md` works _without_ the SVG slide from my [minimal example](https://github.com/hchiam/trying-md2googleslides/blob/master/slides.md).

# Bad: 
If I include the SVG from the example, I get the message `Unable to generate slides: Local images require --use-fileio option`

You can see what I tried [here](https://github.com/hchiam/trying-md2googleslides/blob/master/slides.md). I have a self-describing comment that shows right up to where it works. 

## What else I tried:
I also tried cloning the md2googleslides repo, `cd examples` and running `md2gslides example.md`, but I get this message instead: 
```bash
Unable to generate slides: { ProbeError: unrecognized file format
    at ParserStream.parserEnd (/Users/howard/.nvm/versions/node/v10.13.0/lib/node_modules/md2gslides/node_modules/probe-image-size/stream.js:29:24)
    at Object.onceWrapper (events.js:273:13)
    at ParserStream.emit (events.js:182:13)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'ProbeError',
  message: 'unrecognized file format',
  code: 'ECONTENT' }
```

Sorry if I'm missing something obvious. This tool is interesting.

**Comment by vitaliysobur** [comment]
Hi @hchiam, 

I just ran your [example deck](https://github.com/hchiam/trying-md2googleslides/blob/master/slides.md) using the following command `md2gslides --use-fileio slides.md`. As the result I was able to generate a google slides deck with the google logo on the last slide. 

Can you please check if it works for you?
Hope it will help. I might understood the issue wrong though.

**Comment by hchiam** [comment]
Thanks! That worked for me. :) Totally did not know about that [flag](https://www.google.com/search?q=md2gslides+%22--use-fileio%22). Maybe it should be included in documentation? Or maybe not. Feel free to close this issue, whichever way the team decides.
